"""initial schema

Revision ID: fd1c28a1d461
Revises: 
Create Date: 2026-08-18 13:04:04.178591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = 'fd1c28a1d461'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('school', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('avatar_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('avatar_content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('avatar_updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('avatarmodel',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('thumbnail_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avatarmodel_user_id'), 'avatarmodel', ['user_id'], unique=False)
    op.create_table('backgroundimage',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backgroundimage_user_id'), 'backgroundimage', ['user_id'], unique=False)
    op.create_table('passwordresettoken',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passwordresettoken_token_hash'), 'passwordresettoken', ['token_hash'], unique=True)
    op.create_index(op.f('ix_passwordresettoken_user_id'), 'passwordresettoken', ['user_id'], unique=False)
    op.create_table('userapikey',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('encrypted_api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('masked_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('api_base', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('arcana_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userapikey_user_id'), 'userapikey', ['user_id'], unique=False)
    op.create_table('project',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('llm_api_key_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('llm_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('preprompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('avatar_model_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('avatar_background_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('grade_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pedagogy', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('safety', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lesson_behavior', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('custom_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prompt_mode_auto', sa.Boolean(), nullable=False),
    sa.Column('manual_system_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('creativity', sa.Float(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('share_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('save_conversations', sa.Boolean(), nullable=False),
    sa.Column('survey_before_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('survey_before_enabled', sa.Boolean(), nullable=False),
    sa.Column('survey_after_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('survey_after_enabled', sa.Boolean(), nullable=False),
    sa.Column('tts_enabled', sa.Boolean(), nullable=False),
    sa.Column('tts_api_key_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tts_voice', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('spoken_language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stt_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['llm_api_key_id'], ['userapikey.id'], ),
    sa.ForeignKeyConstraint(['tts_api_key_id'], ['userapikey.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_llm_api_key_id'), 'project', ['llm_api_key_id'], unique=False)
    op.create_index(op.f('ix_project_share_slug'), 'project', ['share_slug'], unique=True)
    op.create_index(op.f('ix_project_tts_api_key_id'), 'project', ['tts_api_key_id'], unique=False)
    op.create_index(op.f('ix_project_user_id'), 'project', ['user_id'], unique=False)
    op.create_table('conversation',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('visitor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('messages_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_project_id'), 'conversation', ['project_id'], unique=False)
    op.create_index(op.f('ix_conversation_visitor_id'), 'conversation', ['visitor_id'], unique=False)
    op.create_table('projectaccess',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('visitor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('accessed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projectaccess_accessed_at'), 'projectaccess', ['accessed_at'], unique=False)
    op.create_index(op.f('ix_projectaccess_project_id'), 'projectaccess', ['project_id'], unique=False)
    op.create_index(op.f('ix_projectaccess_visitor_id'), 'projectaccess', ['visitor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projectaccess_visitor_id'), table_name='projectaccess')
    op.drop_index(op.f('ix_projectaccess_project_id'), table_name='projectaccess')
    op.drop_index(op.f('ix_projectaccess_accessed_at'), table_name='projectaccess')
    op.drop_table('projectaccess')
    op.drop_index(op.f('ix_conversation_visitor_id'), table_name='conversation')
    op.drop_index(op.f('ix_conversation_project_id'), table_name='conversation')
    op.drop_table('conversation')
    op.drop_index(op.f('ix_project_user_id'), table_name='project')
    op.drop_index(op.f('ix_project_tts_api_key_id'), table_name='project')
    op.drop_index(op.f('ix_project_share_slug'), table_name='project')
    op.drop_index(op.f('ix_project_llm_api_key_id'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_userapikey_user_id'), table_name='userapikey')
    op.drop_table('userapikey')
    op.drop_index(op.f('ix_passwordresettoken_user_id'), table_name='passwordresettoken')
    op.drop_index(op.f('ix_passwordresettoken_token_hash'), table_name='passwordresettoken')
    op.drop_table('passwordresettoken')
    op.drop_index(op.f('ix_backgroundimage_user_id'), table_name='backgroundimage')
    op.drop_table('backgroundimage')
    op.drop_index(op.f('ix_avatarmodel_user_id'), table_name='avatarmodel')
    op.drop_table('avatarmodel')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
