"""
Error Codes

Stable, machine-readable codes used as the `detail` of HTTPException (and as ValueError
messages in Pydantic validators) across the API, instead of hardcoded German prose.

Why? The frontend shows these to the user and needs to translate them (German/English, see
frontend/src/i18n). A stable code lets the frontend own the display text for every language;
the backend only ever says *what* went wrong, never *how* to phrase it.

How to use:
    from app.core.error_codes import ErrorCode

    raise HTTPException(status_code=401, detail=ErrorCode.SESSION_EXPIRED)
    # or, in a Pydantic field/model validator:
    raise ValueError(ErrorCode.PASSWORD_TOO_SHORT)

Every code added here needs a matching `errors.<CODE>` entry in both
frontend/src/i18n/locales/de.json and en.json.
"""


class ErrorCode:
    """Namespace of error code constants — plain strings, not an Enum, so they drop straight
    into `detail=...`/`ValueError(...)` without an extra `.value`."""

    NOT_AUTHENTICATED = "NOT_AUTHENTICATED"
    SESSION_EXPIRED = "SESSION_EXPIRED"
    PROJECT_NOT_FOUND = "PROJECT_NOT_FOUND"
    PROJECT_NOT_FOUND_OR_UNPUBLISHED = "PROJECT_NOT_FOUND_OR_UNPUBLISHED"
    INVALID_BUILTIN_AVATAR = "INVALID_BUILTIN_AVATAR"
    PROJECT_IMPORT_INVALID = "PROJECT_IMPORT_INVALID"
    PROJECT_IMPORT_FILE_TOO_LARGE = "PROJECT_IMPORT_FILE_TOO_LARGE"
    CONVERSATION_NOT_FOUND = "CONVERSATION_NOT_FOUND"

    REGISTRATION_DISABLED = "REGISTRATION_DISABLED"
    EMAIL_ALREADY_REGISTERED = "EMAIL_ALREADY_REGISTERED"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    ACCOUNT_DISABLED = "ACCOUNT_DISABLED"
    RESET_LINK_INVALID = "RESET_LINK_INVALID"
    CURRENT_PASSWORD_INCORRECT = "CURRENT_PASSWORD_INCORRECT"
    PASSWORD_TOO_SHORT = "PASSWORD_TOO_SHORT"
    PASSWORD_TOO_LONG = "PASSWORD_TOO_LONG"

    PROFILE_PICTURE_TOO_LARGE = "PROFILE_PICTURE_TOO_LARGE"
    PROFILE_PICTURE_INVALID_TYPE = "PROFILE_PICTURE_INVALID_TYPE"
    PROFILE_PICTURE_NOT_FOUND = "PROFILE_PICTURE_NOT_FOUND"

    AVATAR_FILE_INVALID_TYPE = "AVATAR_FILE_INVALID_TYPE"
    AVATAR_FILE_TOO_LARGE = "AVATAR_FILE_TOO_LARGE"
    AVATAR_FILE_INVALID_CONTENT = "AVATAR_FILE_INVALID_CONTENT"
    AVATAR_NOT_FOUND = "AVATAR_NOT_FOUND"
    AVATAR_THUMBNAIL_TOO_LARGE = "AVATAR_THUMBNAIL_TOO_LARGE"
    AVATAR_THUMBNAIL_INVALID = "AVATAR_THUMBNAIL_INVALID"
    AVATAR_THUMBNAIL_NOT_FOUND = "AVATAR_THUMBNAIL_NOT_FOUND"
    VOICE_CLIP_NOT_FOUND = "VOICE_CLIP_NOT_FOUND"
    VOICE_CLIP_TOO_LARGE = "VOICE_CLIP_TOO_LARGE"
    VOICE_CLIP_INVALID_AUDIO = "VOICE_CLIP_INVALID_AUDIO"
    VOICE_CLIP_TOO_SHORT = "VOICE_CLIP_TOO_SHORT"
    VOICE_CLIP_TOO_LONG = "VOICE_CLIP_TOO_LONG"
    VOICE_CLIP_CONSENT_REQUIRED = "VOICE_CLIP_CONSENT_REQUIRED"
    VOICE_CLIP_NAME_REQUIRED = "VOICE_CLIP_NAME_REQUIRED"
    VOICE_PREVIEW_FAILED = "VOICE_PREVIEW_FAILED"

    BACKGROUND_INVALID_TYPE = "BACKGROUND_INVALID_TYPE"
    BACKGROUND_FILE_TOO_LARGE = "BACKGROUND_FILE_TOO_LARGE"
    BACKGROUND_INVALID_CONTENT = "BACKGROUND_INVALID_CONTENT"
    BACKGROUND_NOT_FOUND = "BACKGROUND_NOT_FOUND"

    UNKNOWN_API_KEY = "UNKNOWN_API_KEY"
    API_KEY_NOT_FOUND = "API_KEY_NOT_FOUND"
    NO_LLM_MODEL_SELECTED = "NO_LLM_MODEL_SELECTED"
    LLM_REQUEST_FAILED = "LLM_REQUEST_FAILED"
    STT_REQUEST_FAILED = "STT_REQUEST_FAILED"
    VOICE_INPUT_DISABLED = "VOICE_INPUT_DISABLED"
    VOICE_INPUT_UNAVAILABLE = "VOICE_INPUT_UNAVAILABLE"
    UNSUPPORTED_AUDIO_FORMAT = "UNSUPPORTED_AUDIO_FORMAT"
    AUDIO_FILE_TOO_LARGE = "AUDIO_FILE_TOO_LARGE"
    CHAT_UNAVAILABLE = "CHAT_UNAVAILABLE"
    CHAT_MESSAGE_EMPTY = "CHAT_MESSAGE_EMPTY"
    CHAT_MESSAGE_TOO_LONG = "CHAT_MESSAGE_TOO_LONG"
    CHAT_PASSWORD_TOO_SHORT = "CHAT_PASSWORD_TOO_SHORT"
    CHAT_PASSWORD_TOO_LONG = "CHAT_PASSWORD_TOO_LONG"
    CHAT_PASSWORD_INCORRECT = "CHAT_PASSWORD_INCORRECT"
    CHAT_UNLOCK_REQUIRED = "CHAT_UNLOCK_REQUIRED"
    PROJECT_NOT_PASSWORD_PROTECTED = "PROJECT_NOT_PASSWORD_PROTECTED"
    VISITOR_NAME_REQUIRED = "VISITOR_NAME_REQUIRED"
    TEMPERATURE_OUT_OF_RANGE = "TEMPERATURE_OUT_OF_RANGE"
    TOP_P_OUT_OF_RANGE = "TOP_P_OUT_OF_RANGE"

    START_PROMPT_REQUIRED = "START_PROMPT_REQUIRED"
    TTS_NOT_CONFIGURED = "TTS_NOT_CONFIGURED"
    START_AUDIO_GENERATION_FAILED = "START_AUDIO_GENERATION_FAILED"
    START_AUDIO_NOT_FOUND = "START_AUDIO_NOT_FOUND"

    RATE_LIMIT_CHAT = "RATE_LIMIT_CHAT"
    RATE_LIMIT_TRANSCRIBE = "RATE_LIMIT_TRANSCRIBE"
    RATE_LIMIT_CHAT_UNLOCK = "RATE_LIMIT_CHAT_UNLOCK"
    RATE_LIMIT_LOGIN = "RATE_LIMIT_LOGIN"
    RATE_LIMIT_REGISTER = "RATE_LIMIT_REGISTER"
    RATE_LIMIT_GENERIC = "RATE_LIMIT_GENERIC"

    ADMIN_REQUIRED = "ADMIN_REQUIRED"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    CANNOT_DISABLE_SELF = "CANNOT_DISABLE_SELF"
    LAST_ADMIN_PROTECTED = "LAST_ADMIN_PROTECTED"

    UNKNOWN_PROVIDER = "UNKNOWN_PROVIDER"
    PROVIDER_UNSUPPORTED_KEY_TYPE = "PROVIDER_UNSUPPORTED_KEY_TYPE"
    PROVIDER_NEEDS_BASE_URL = "PROVIDER_NEEDS_BASE_URL"
    PROVIDER_BASE_URL_NOT_ALLOWED = "PROVIDER_BASE_URL_NOT_ALLOWED"
    PROVIDER_NEEDS_ARCANA_ID = "PROVIDER_NEEDS_ARCANA_ID"
    PROVIDER_NEEDS_API_KEY = "PROVIDER_NEEDS_API_KEY"
    MODEL_REQUIRED = "MODEL_REQUIRED"
    ARCANA_KEY_MISSING_MODEL = "ARCANA_KEY_MISSING_MODEL"
    ARCANA_KEY_MISSING_ID = "ARCANA_KEY_MISSING_ID"
    API_KEY_NO_TESTABLE_MODEL = "API_KEY_NO_TESTABLE_MODEL"
    TTS_KEY_MISSING_MODEL = "TTS_KEY_MISSING_MODEL"
    TTS_KEY_TEST_NEEDS_VOICE = "TTS_KEY_TEST_NEEDS_VOICE"
    TTS_PROVIDER_UNSUPPORTED = "TTS_PROVIDER_UNSUPPORTED"
    CARTESIA_KEY_MISSING_MODEL = "CARTESIA_KEY_MISSING_MODEL"
    STT_KEY_MISSING_MODEL = "STT_KEY_MISSING_MODEL"
    STT_PROVIDER_UNSUPPORTED = "STT_PROVIDER_UNSUPPORTED"
    EMBEDDING_KEY_MISSING_MODEL = "EMBEDDING_KEY_MISSING_MODEL"

    KNOWLEDGE_DISABLED = "KNOWLEDGE_DISABLED"
    KNOWLEDGE_SERVICE_UNAVAILABLE = "KNOWLEDGE_SERVICE_UNAVAILABLE"
    KNOWLEDGE_SERVICE_ERROR = "KNOWLEDGE_SERVICE_ERROR"
    KNOWLEDGE_BASE_NOT_FOUND = "KNOWLEDGE_BASE_NOT_FOUND"
    KNOWLEDGE_BASE_NAME_REQUIRED = "KNOWLEDGE_BASE_NAME_REQUIRED"
    KNOWLEDGE_BASE_LIMIT_REACHED = "KNOWLEDGE_BASE_LIMIT_REACHED"
    KNOWLEDGE_DOCUMENT_NOT_FOUND = "KNOWLEDGE_DOCUMENT_NOT_FOUND"
    KNOWLEDGE_DOCUMENT_LIMIT_REACHED = "KNOWLEDGE_DOCUMENT_LIMIT_REACHED"
    KNOWLEDGE_DOCUMENT_DUPLICATE = "KNOWLEDGE_DOCUMENT_DUPLICATE"
    KNOWLEDGE_QUOTA_EXCEEDED = "KNOWLEDGE_QUOTA_EXCEEDED"
    KNOWLEDGE_UPLOAD_CONSENT_REQUIRED = "KNOWLEDGE_UPLOAD_CONSENT_REQUIRED"
    KNOWLEDGE_EMBEDDING_KEY_INVALID = "KNOWLEDGE_EMBEDDING_KEY_INVALID"
    KNOWLEDGE_LIMIT_ABOVE_CEILING = "KNOWLEDGE_LIMIT_ABOVE_CEILING"
    RATE_LIMIT_KNOWLEDGE_UPLOAD = "RATE_LIMIT_KNOWLEDGE_UPLOAD"
    RATE_LIMIT_EVALUATION = "RATE_LIMIT_EVALUATION"
    # The knowledge service's own codes (rag/app/errors.py), passed on with this prefix so they
    # can't collide with the backend's — see features/knowledge/rag_client.py::knowledge_code.
    KNOWLEDGE_UNSUPPORTED_FILE_TYPE = "KNOWLEDGE_UNSUPPORTED_FILE_TYPE"
    KNOWLEDGE_FILE_TYPE_MISMATCH = "KNOWLEDGE_FILE_TYPE_MISMATCH"
    KNOWLEDGE_FILE_TOO_LARGE = "KNOWLEDGE_FILE_TOO_LARGE"
    KNOWLEDGE_FILE_EMPTY = "KNOWLEDGE_FILE_EMPTY"
    KNOWLEDGE_DOCX_INVALID = "KNOWLEDGE_DOCX_INVALID"
    KNOWLEDGE_DOCX_MACROS = "KNOWLEDGE_DOCX_MACROS"
    KNOWLEDGE_ARCHIVE_TOO_LARGE = "KNOWLEDGE_ARCHIVE_TOO_LARGE"
    KNOWLEDGE_PDF_ENCRYPTED = "KNOWLEDGE_PDF_ENCRYPTED"
    KNOWLEDGE_TOO_MANY_PAGES = "KNOWLEDGE_TOO_MANY_PAGES"
    KNOWLEDGE_NO_EXTRACTABLE_TEXT = "KNOWLEDGE_NO_EXTRACTABLE_TEXT"
    KNOWLEDGE_FILE_TOO_COMPLEX = "KNOWLEDGE_FILE_TOO_COMPLEX"
    KNOWLEDGE_PARSE_TIMEOUT = "KNOWLEDGE_PARSE_TIMEOUT"
    KNOWLEDGE_PARSE_FAILED = "KNOWLEDGE_PARSE_FAILED"
    KNOWLEDGE_DOCLING_UNAVAILABLE = "KNOWLEDGE_DOCLING_UNAVAILABLE"
    KNOWLEDGE_DOCLING_FAILED = "KNOWLEDGE_DOCLING_FAILED"
    KNOWLEDGE_EMBEDDING_FAILED = "KNOWLEDGE_EMBEDDING_FAILED"
    KNOWLEDGE_EMBEDDING_MODEL_NOT_ALLOWED = "KNOWLEDGE_EMBEDDING_MODEL_NOT_ALLOWED"
    KNOWLEDGE_EMBEDDING_KEY_MISSING = "KNOWLEDGE_EMBEDDING_KEY_MISSING"
    KNOWLEDGE_EMBEDDING_MISMATCH = "KNOWLEDGE_EMBEDDING_MISMATCH"
    KNOWLEDGE_INTERRUPTED = "KNOWLEDGE_INTERRUPTED"
    KNOWLEDGE_RETRY_NOT_POSSIBLE = "KNOWLEDGE_RETRY_NOT_POSSIBLE"

    # Quality evaluation (features/evaluation/)
    EVALUATION_DISABLED = "EVALUATION_DISABLED"
    EVALUATION_SERVICE_UNAVAILABLE = "EVALUATION_SERVICE_UNAVAILABLE"
    EVALUATION_TEST_SET_NOT_FOUND = "EVALUATION_TEST_SET_NOT_FOUND"
    EVALUATION_TEST_CASE_NOT_FOUND = "EVALUATION_TEST_CASE_NOT_FOUND"
    EVALUATION_RUN_NOT_FOUND = "EVALUATION_RUN_NOT_FOUND"
    EVALUATION_NAME_REQUIRED = "EVALUATION_NAME_REQUIRED"
    EVALUATION_QUESTION_REQUIRED = "EVALUATION_QUESTION_REQUIRED"
    EVALUATION_TEST_SET_FULL = "EVALUATION_TEST_SET_FULL"
    EVALUATION_CSV_INVALID = "EVALUATION_CSV_INVALID"
    EVALUATION_NO_PASSAGES = "EVALUATION_NO_PASSAGES"
    EVALUATION_NO_CASES = "EVALUATION_NO_CASES"
    EVALUATION_TOO_MANY_CASES = "EVALUATION_TOO_MANY_CASES"
    EVALUATION_RUN_ACTIVE = "EVALUATION_RUN_ACTIVE"
    EVALUATION_GENERATION_ACTIVE = "EVALUATION_GENERATION_ACTIVE"
    EVALUATION_RUN_NOT_ACTIVE = "EVALUATION_RUN_NOT_ACTIVE"
    EVALUATION_JUDGE_KEY_INVALID = "EVALUATION_JUDGE_KEY_INVALID"
    EVALUATION_JUDGE_FAILED = "EVALUATION_JUDGE_FAILED"
    EVALUATION_LLM_FAILED = "EVALUATION_LLM_FAILED"
    EVALUATION_INTERRUPTED = "EVALUATION_INTERRUPTED"
    EVALUATION_KEY_DELETED = "EVALUATION_KEY_DELETED"
