"""
Error Codes

Stable, machine-readable codes used as the `detail` of HTTPException (and as ValueError
messages in Pydantic validators) across the API, instead of hardcoded German prose.

Why? The frontend shows these to the user and needs to translate them (German/English, see
frontend/src/i18n). A stable code lets the frontend own the display text for every language;
the backend only ever says *what* went wrong, never *how* to phrase it.

How to use:
    from app.core.error_codes import ErrorCode

    raise HTTPException(status_code=401, detail=ErrorCode.SESSION_EXPIRED)
    # or, in a Pydantic field/model validator:
    raise ValueError(ErrorCode.PASSWORD_TOO_SHORT)

Every code added here needs a matching `errors.<CODE>` entry in both
frontend/src/i18n/locales/de.json and en.json.
"""


class ErrorCode:
    """Namespace of error code constants — plain strings, not an Enum, so they drop straight
    into `detail=...`/`ValueError(...)` without an extra `.value`."""

    NOT_AUTHENTICATED = "NOT_AUTHENTICATED"
    SESSION_EXPIRED = "SESSION_EXPIRED"
    PROJECT_NOT_FOUND = "PROJECT_NOT_FOUND"
    PROJECT_NOT_FOUND_OR_UNPUBLISHED = "PROJECT_NOT_FOUND_OR_UNPUBLISHED"

    REGISTRATION_DISABLED = "REGISTRATION_DISABLED"
    EMAIL_ALREADY_REGISTERED = "EMAIL_ALREADY_REGISTERED"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    RESET_LINK_INVALID = "RESET_LINK_INVALID"
    CURRENT_PASSWORD_INCORRECT = "CURRENT_PASSWORD_INCORRECT"
    PASSWORD_TOO_SHORT = "PASSWORD_TOO_SHORT"
    PASSWORD_TOO_LONG = "PASSWORD_TOO_LONG"

    PROFILE_PICTURE_TOO_LARGE = "PROFILE_PICTURE_TOO_LARGE"
    PROFILE_PICTURE_INVALID_TYPE = "PROFILE_PICTURE_INVALID_TYPE"
    PROFILE_PICTURE_NOT_FOUND = "PROFILE_PICTURE_NOT_FOUND"

    AVATAR_FILE_INVALID_TYPE = "AVATAR_FILE_INVALID_TYPE"
    AVATAR_FILE_TOO_LARGE = "AVATAR_FILE_TOO_LARGE"
    AVATAR_FILE_INVALID_CONTENT = "AVATAR_FILE_INVALID_CONTENT"
    AVATAR_NOT_FOUND = "AVATAR_NOT_FOUND"
    AVATAR_THUMBNAIL_TOO_LARGE = "AVATAR_THUMBNAIL_TOO_LARGE"
    AVATAR_THUMBNAIL_INVALID = "AVATAR_THUMBNAIL_INVALID"
    AVATAR_THUMBNAIL_NOT_FOUND = "AVATAR_THUMBNAIL_NOT_FOUND"

    BACKGROUND_INVALID_TYPE = "BACKGROUND_INVALID_TYPE"
    BACKGROUND_FILE_TOO_LARGE = "BACKGROUND_FILE_TOO_LARGE"
    BACKGROUND_INVALID_CONTENT = "BACKGROUND_INVALID_CONTENT"
    BACKGROUND_NOT_FOUND = "BACKGROUND_NOT_FOUND"

    UNKNOWN_API_KEY = "UNKNOWN_API_KEY"
    API_KEY_NOT_FOUND = "API_KEY_NOT_FOUND"
    NO_LLM_MODEL_SELECTED = "NO_LLM_MODEL_SELECTED"
    LLM_REQUEST_FAILED = "LLM_REQUEST_FAILED"
    STT_REQUEST_FAILED = "STT_REQUEST_FAILED"
    VOICE_INPUT_DISABLED = "VOICE_INPUT_DISABLED"
    VOICE_INPUT_UNAVAILABLE = "VOICE_INPUT_UNAVAILABLE"
    UNSUPPORTED_AUDIO_FORMAT = "UNSUPPORTED_AUDIO_FORMAT"
    AUDIO_FILE_TOO_LARGE = "AUDIO_FILE_TOO_LARGE"
    CHAT_UNAVAILABLE = "CHAT_UNAVAILABLE"
    CHAT_PASSWORD_TOO_SHORT = "CHAT_PASSWORD_TOO_SHORT"
    CHAT_PASSWORD_TOO_LONG = "CHAT_PASSWORD_TOO_LONG"
    CHAT_PASSWORD_INCORRECT = "CHAT_PASSWORD_INCORRECT"
    CHAT_UNLOCK_REQUIRED = "CHAT_UNLOCK_REQUIRED"
    PROJECT_NOT_PASSWORD_PROTECTED = "PROJECT_NOT_PASSWORD_PROTECTED"

    RATE_LIMIT_CHAT = "RATE_LIMIT_CHAT"
    RATE_LIMIT_TRANSCRIBE = "RATE_LIMIT_TRANSCRIBE"
    RATE_LIMIT_CHAT_UNLOCK = "RATE_LIMIT_CHAT_UNLOCK"
    RATE_LIMIT_LOGIN = "RATE_LIMIT_LOGIN"
    RATE_LIMIT_REGISTER = "RATE_LIMIT_REGISTER"
    RATE_LIMIT_GENERIC = "RATE_LIMIT_GENERIC"

    ADMIN_REQUIRED = "ADMIN_REQUIRED"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    CANNOT_DISABLE_SELF = "CANNOT_DISABLE_SELF"
    LAST_ADMIN_PROTECTED = "LAST_ADMIN_PROTECTED"

    UNKNOWN_PROVIDER = "UNKNOWN_PROVIDER"
    PROVIDER_UNSUPPORTED_KEY_TYPE = "PROVIDER_UNSUPPORTED_KEY_TYPE"
    PROVIDER_NEEDS_BASE_URL = "PROVIDER_NEEDS_BASE_URL"
    PROVIDER_NEEDS_ARCANA_ID = "PROVIDER_NEEDS_ARCANA_ID"
    PROVIDER_NEEDS_API_KEY = "PROVIDER_NEEDS_API_KEY"
    MODEL_REQUIRED = "MODEL_REQUIRED"
    ARCANA_KEY_MISSING_MODEL = "ARCANA_KEY_MISSING_MODEL"
    ARCANA_KEY_MISSING_ID = "ARCANA_KEY_MISSING_ID"
    API_KEY_NO_TESTABLE_MODEL = "API_KEY_NO_TESTABLE_MODEL"
    TTS_KEY_MISSING_MODEL = "TTS_KEY_MISSING_MODEL"
    TTS_KEY_TEST_NEEDS_VOICE = "TTS_KEY_TEST_NEEDS_VOICE"
    TTS_PROVIDER_UNSUPPORTED = "TTS_PROVIDER_UNSUPPORTED"
    CARTESIA_KEY_MISSING_MODEL = "CARTESIA_KEY_MISSING_MODEL"
